# Generated by Django 3.1.4 on 2021-02-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('shortname', models.TextField(max_length=100)),
                ('image', models.ImageField(default='null', upload_to='career', verbose_name='Miniatura')),
                ('state', models.CharField(max_length=150)),
            ],
        ),
    ]
